name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  screenshots:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3

      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: "true"

      - name: screenshots-ci-action
        uses: flameddd/screenshots-ci-action@master
        with:
          url: https://gobluebro.github.io/Mock-Ichiban-Kuji-Website/
          noCommitHashFileName: true

      - uses: actions/upload-artifact@v3
        with:
          path: screenshots
          name: Download-screenshots

  download-screenshots:
    runs-on: ubuntu-latest
    needs: screenshots
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Download-screenshots
          path: ./screenshots

      - name: Add and commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
