name: Dispatch screenshots-action workflow
on:
  push:
    branches:
      - main

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: "true"
      - name: screenshots-ci-action
        uses: flameddd/screenshots-ci-action@master
        with:
          url: https://gobluebro.github.io/Mock-Ichiban-Kuji-Website/
      - uses: actions/upload-artifact@v3
        with:
          path: screenshots
          name: Download-screenshots
  download-screenshots:
    runs-on: ubuntu-latest
    needs: screenshots
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: Download-screenshots
          path: ~/screenshots
      - name: Test artifact download
        run: ls -R
      - name: Add and commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
